version: "3"

services:
  feed-generator:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - "NODE_ENV=production"
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.25
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/cert/fullchain.pem:/etc/letsencrypt/fullchain.pem"
      - "./nginx/cert/privkey.pem:/etc/letsencrypt/privkey.pem"
    ports:
      - "443:443"
